Repository ProtonMC/Proton, pull requests merged in 2020-11, with the labels that each got.

#54 Adds more witty comments.
  src/main/java/io/github/protonmc/proton/Proton.java
  src/main/java/io/github/protonmc/proton/mixin/tweaks/CrashReportMixin.java
  src/main/java/io/github/protonmc/proton/module/tweaks/MoreWittyMessages.java
  src/main/resources/proton.accessWidener
  src/main/resources/proton.mixins.json
Labels: enhancement

#55 Checkin' our PRs...
  .github/workflows/pr_checks.yml
Labels: dev feature

#53 Tilt to damage
  src/main/java/io/github/protonmc/proton/mixin/tweaks/LivingEntityMixin.java
  src/main/java/io/github/protonmc/proton/module/tweaks/TiltToDamage.java
  src/main/resources/proton.mixins.json
Labels: feature
